Propose plus thiserror
zingolabs/zingolib pull request #1010
Opened 2024-04-29 18:26 UTC by fluidvanadium

2024-04-29 20:01 UTC, AloeareV requested changes

2024-04-29 20:01 UTC, AloeareV commented on zingolib/src/lightclient/send.rs
> +    pub async fn do_send_proposal(&self) -> Result<Vec<TxId>, String> {
The feature gates and imports would be cleaner if this went into the propose mod.

2024-04-29 21:05 UTC, fluidvanadium commented on zingolib/src/lightclient/send.rs
> +    pub async fn do_send_proposal(&self) -> Result<Vec<TxId>, String> {
its not part of that mod. propose mod is for creating the proposal. send mod includes sending it.

2024-04-30 17:22 UTC, AloeareV approved these changes

2024-04-30 17:22 UTC, merged