implement send-to-self to be created alongside zfz sent value transfer
zingolabs/zingolib pull request #1299
Opened 2024-07-17 16:19 UTC by Oscar-Pepper

2024-07-17 16:42 UTC, fluidvanadium requested changes
overall good, but the zfz test doesnt seem to actually enable ZFZ

2024-07-18 09:41 UTC, Oscar-Pepper commented
> overall good, but the zfz test doesnt seem to actually enable ZFZ

the test is not asserting anything so its actually not finished but the zfz is active, thats the `true` on line 151

2024-07-18 10:15 UTC, Oscar-Pepper commented
ok the new address is added and test is finished, ready for review!

2024-07-18 16:11 UTC, juanky201271 approved these changes

2024-07-18 16:36 UTC, merged