derive USK from seed
zingolabs/zingolib pull request #1309
Opened 2024-07-24 17:25 UTC by fluidvanadium

This is the simplest way to achieve this. If this works we wont have to use the next layer.

2024-07-27 01:45 UTC, zancas commented on zingolib/src/lightclient/send.rs
> +            let unified_spend_key = UnifiedSpendingKey::from_seed(
@Oscar-Pepper how does this interact with taddresses that we've published from transparent keys in the past?

2024-07-27 01:46 UTC, zancas requested changes
I don't understand the implications for backwards compatibility, or how we're testing for maintenance of functionality.

2024-08-20 06:10 UTC, zancas commented
I notice that there's a merge conflict on this.

2024-09-05 21:49 UTC, fluidvanadium commented
this doesnt work. perhaps the hack hasnt been given enough credit

2024-09-05 21:50 UTC, closed without merging