Update lrz for 320
zingolabs/zingolib pull request #1357
Opened 2024-09-05 15:42 UTC by fluidvanadium

2024-09-06 14:02 UTC, zancas commented on libtonode-tests/tests/concrete.rs
> +            .status(ConfirmationStatus::Transmitted(BlockHeight::from_u32(7)))
This belongs in a different PR.

2024-09-06 14:03 UTC, zancas requested changes
It seems like two PRs are mixed together..  I am guessing the that LRZ update is atop another PR?

2024-09-09 17:24 UTC, AloeareV commented on zingolib/src/wallet/transaction_records_by_id/trait_inputsource.rs
> -    /// Returns a list of unspent transparent UTXOs that appear in the chain at heights up to and
I don't see these added back anywhere...does the new librustzcash make them no longer needed?

2024-09-09 17:48 UTC, fluidvanadium commented on zingolib/src/wallet/transaction_records_by_id/trait_inputsource.rs
> -    /// Returns a list of unspent transparent UTXOs that appear in the chain at heights up to and
i am not sure these were ever needed

2024-09-09 19:32 UTC, zancas commented
What's the state of this PR?  Is it superseded?

2024-09-09 19:37 UTC, AloeareV commented on zingolib/src/wallet/transaction_records_by_id/trait_inputsource.rs
> -    /// Returns a list of unspent transparent UTXOs that appear in the chain at heights up to and
Running against latest dev with the following diff, several tests fail. They're needed on latest dev. If they're not needed with new librustzcash, that's great! 
```diff
git diff
diff --git a/zingolib/src/wallet/tx_map_and_maybe_trees/trait_stub_inputsource.rs b/zingolib/src/wallet/tx_map_and_maybe_trees/trait_stub_inputsource.rs
index f9abbb77..aa90003e 100644
--- a/zingolib/src/wallet/tx_map_and_maybe_trees/trait_stub_inputsource.rs
+++ b/zingolib/src/wallet/tx_map_and_maybe_trees/trait_stub_inputsource.rs
@@ -44,22 +44,4 @@ impl InputSource for TxMapAndMaybeTrees {
             .select_spendable_notes(account, target_value, sources, anchor_height, exclude)
             .map_err(TxMapAndMaybeTreesTraitError::InputSource)
     }
-
-    fn get_unspent_transparent_output(
-        &self,
-        _outpoint: &zcash_primitives::transaction::components::OutPoint,
-    ) -> Result<Option<zcash_client_backend::wallet::WalletTransparentOutput>, Self::Error> {
-        unimplemented!()
-    }
-
-    fn get_unspent_transparent_outputs(
-        &self,
-        address: &zcash_primitives::legacy::TransparentAddress,
-        max_height: zcash_primitives::consensus::BlockHeight,
-        exclude: &[zcash_primitives::transaction::components::OutPoint],
-    ) -> Result<Vec<zcash_client_backend::wallet::WalletTransparentOutput>, Self::Error> {
-        self.transaction_records_by_id
-            .get_unspent_transparent_outputs(address, max_height, exclude)
-            .map_err(TxMapAndMaybeTreesTraitError::InputSource)
-    }
 }
 ```

2024-09-09 19:59 UTC, closed without merging

2024-09-09 19:59 UTC, fluidvanadium commented
this PR is being pulled into smaller pieces

2024-09-09 20:03 UTC, zancas commented
OK I will mention it in the tracking Issue, or should we close it?