cargo update
zingolabs/zingolib pull request #1406
Opened 2024-09-18 18:17 UTC by fluidvanadium

2024-09-19 10:11 UTC, Oscar-Pepper requested changes
@zancas recently had a PR that removed this so there is only one source of truth for version, the rust-toolchain file. could you write in the PR description what issue this is solving so we can have a dsicussion?

2024-09-23 02:33 UTC, fluidvanadium commented
> @zancas recently had a PR that removed this so there is only one source of truth for version, the rust-toolchain file. could you write in the PR description what issue this is solving so we can have a dsicussion?

description improved

2024-09-23 03:07 UTC, fluidvanadium commented
when i run cargo install cargo-nextest locally, i get the following line:
`Compiling guppy v0.17.7`
in contrast to this here error
`Location: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/guppy-0.17.1/src/graph/build.rs:749`

2024-09-26 10:57 UTC, Oscar-Pepper commented
CI is working fine now

2024-09-26 10:57 UTC, closed without merging