changed runs-on to self-hosted in `ci.yaml`
zingolabs/zingolib pull request #1458
Opened 2024-10-17 01:13 UTC by nachog00

2024-10-17 02:01 UTC, zancas approved these changes, later dismissed

2024-10-28 22:18 UTC, zancas commented
Hi @nachog00 is this PR still active?  Or has it been superceded?

2024-10-28 23:21 UTC, nachog00 commented
> Hi @nachog00 is this PR still active? Or has it been superceded?

no. When self hosted runners handle jobs correctly, merging this will make all jobs be picked up by them.

2024-10-30 21:59 UTC, fluidvanadium requested changes

2024-10-30 21:59 UTC, fluidvanadium commented on .github/workflows/test.yaml
> +          fi
since sudo doesnt work in a container, this line needs to go

2024-10-30 22:21 UTC, fluidvanadium approved these changes
buenok

2024-10-30 22:42 UTC, zancas approved these changes

2024-10-30 22:42 UTC, zancas commented
Since this is blocked on CI... and since it should speed up CI, I am going to merge it.

2024-10-30 22:43 UTC, merged