Add Spacers and Points in zingocli balance command
zingolabs/zingolib pull request #1464
Opened 2024-10-21 15:59 UTC by fluidvanadium

Adding a decimal point allows easy estimation of zec per zatoshi.

2024-10-22 01:52 UTC, zancas commented
Is this moving us towards reproducing the vaporizing transaction bug?

2024-10-22 18:34 UTC, zancas commented on zingolib/src/lightclient.rs
> +fn format_option_zatoshis(ioz: &Option<u64>) -> String {
I don't know what "`ioz`" means.

2024-10-22 18:37 UTC, zancas commented
It looks like this crate has been downloaded aroun 15_000_000 times:

https://crates.io/crates/num-format

Why don't we us it?

2024-10-22 18:41 UTC, zancas requested changes
Let's use num-format.

2024-10-22 18:44 UTC, zancas commented
I really like the idea of a more useful/readable zingocli interface.   I don't like the idea of writing our own reimplementation of standard logic.   Let's use the thing that's "off-the-shelf".

2024-10-23 18:59 UTC, fluidvanadium commented
> It looks like this crate has been downloaded aroun 15_000_000 times:
> 
> https://crates.io/crates/num-format
> 
> Why don't we us it?

the answer is: num-format doesnt specifically make use of the 10,000,000 mark for Satoshis

2024-10-30 01:12 UTC, zancas commented on zingolib/src/lightclient.rs
> +fn format_option_zatoshis(ioz: &Option<u64>) -> String {
Is it like "input_of_zatoshis"?    Could we name this parameter:  "zats"?

2024-10-30 01:16 UTC, zancas approved these changes

2024-10-30 01:16 UTC, merged