Restore order for value_transfers and messages
zingolabs/zingolib pull request #1525
Opened 2024-11-16 00:27 UTC by dorianvp

This PR fixes `value_transfers` and `messages_containing`, as they had the inverse order... sorry @juanky201271. It also adds more assertions.

2024-11-16 00:30 UTC, zancas submitted a review, later dismissed

2024-11-16 00:51 UTC, zancas commented
Looks like we need to check the full test suite for regressions.

2024-11-16 01:30 UTC, juanky201271 submitted a review, later dismissed
Well, looks good to me...

2024-11-16 16:27 UTC, zancas requested changes
Let's document a Comprehensive Test Run, against this feature.

2024-11-17 18:55 UTC, dorianvp commented
------------
     Summary [ 788.514s] 334 tests run: 334 passed (109 slow), 30 skipped

git show -s
commit 994103544b2385b9ef4c8f12a5ca4ad4247a8b43 (HEAD, dorian/fix-vt-message-order)
Author: dorianvp <dariovp01@gmail.com>
Date:   Sun Nov 17 14:40:26 2024 -0300

    test: add doc & remove println

2024-11-18 15:24 UTC, AloeareV requested changes

2024-11-18 15:24 UTC, AloeareV commented on zingolib/src/lightclient/describe.rs
> -        for tx in transaction_summaries.iter() {
Can we make this into an argument that the command takes, that optionally reverses it? I would like to be able to keep earliest-first order in my zingocli usage.

2024-11-18 17:21 UTC, AloeareV approved these changes

2024-11-18 18:12 UTC, zancas approved these changes

2024-11-18 18:12 UTC, merged