Don't unwrap a tree that might not be there
zingolabs/zingolib pull request #504
Opened 2023-09-21 17:56 UTC by AloeareV

2023-09-21 18:02 UTC, zancas commented on zingolib/src/wallet.rs
> +            .ok()
My thought experiment is this:

If we had the **right** name in place, when this was first written would it have become obvious to the developer that a critical edge case was being overlooked?

Also....   I notice that we're replacing an `unwrap`..  this makes me skeptical about a previously held belief that "all the unwraps were reasonabile".

2023-09-21 18:03 UTC, zancas approved these changes
@fluidvanadium can you make the names **make** sense?   What's this code doing?  Like maybe the original `fn` should have been more carefully named:

`fn get_legacy_frontiers_except_in_real_world_edge_case_when_tree_is_empty`

2023-09-21 18:14 UTC, zancas requested changes
Let's ask @AArnott to test this.

2023-09-21 19:23 UTC, zancas commented
I converted this to a draft when @AArnott 's (manual) test failed.

2023-09-24 15:15 UTC, zancas commented
@fluidvanadium @Oscar-Pepper @AloeareV @AArnott do we have a test that shows that this change to our `dev` branch fixes something?

How hard would it be to produce such a test?

2023-09-24 21:38 UTC, AArnott commented
Yes, it should be pretty straightforward for me to write the rust code that reproduces the failure I was seeing. I've never written a test in this repo before so the hardest part may be figuring out where and how to best do it.
Also, my test would initially express a dependency on a live lightwalletd server. If you avoid such network dependencies in preference to locally hosted servers, that's fine, but I don't know how to set that up and I'm not certain it'll repro in that configuration.

2023-09-25 23:23 UTC, fluidvanadium approved these changes
yup

2023-09-26 03:04 UTC, fluidvanadium commented
fixes https://github.com/zingolabs/zingolib/issues/520
i believe that issue was introduced by a librustzcash update

2023-09-26 03:49 UTC, fluidvanadium commented
> Yes, it should be pretty straightforward for me to write the rust code that reproduces the failure I was seeing. I've never written a test in this repo before so the hardest part may be figuring out where and how to best do it. Also, my test would initially express a dependency on a live lightwalletd server. If you avoid such network dependencies in preference to locally hosted servers, that's fine, but I don't know how to set that up and I'm not certain it'll repro in that configuration.

ive found it difficult to repro with locally hosted servers. connecting to the live server would be fine im sure. i would love to see this test

2023-09-26 16:01 UTC, merged

2023-09-26 17:54 UTC, zancas commented
@fluidvanadium @Oscar-Pepper @AloeareV @AArnott do we have a test that shows that this change to our `dev` branch fixes something?

How hard would it be to produce such a test?