Config
zingolabs/zingolib pull request #804
Opened 2024-02-05 17:34 UTC by fluidvanadium

ZingoConfigBuilder is now fluent and doctested

2024-02-12 21:13 UTC, AloeareV requested changes, later dismissed

2024-02-12 21:13 UTC, AloeareV commented on zingoconfig/src/lib.rs
> +    pub fn set_lightwalletd_uri(&mut self, lightwalletd_uri: http::Uri) -> &Self {
In order to chain multiple calls this needs to return a `&mut Self`
```suggestion
    pub fn set_lightwalletd_uri(&mut self, lightwalletd_uri: http::Uri) -> &mut Self {
```

2024-02-12 21:13 UTC, AloeareV commented on zingoconfig/src/lib.rs
> +    pub fn set_chain(&mut self, chain: ChainType) -> &Self {
As above
```suggestion
    pub fn set_chain(&mut self, chain: ChainType) -> &mut Self {
```

2024-02-12 21:13 UTC, AloeareV commented on zingoconfig/src/lib.rs
> +    pub fn set_wallet_dir(&mut self, dir: PathBuf) -> &Self {
^^
```suggestion
    pub fn set_wallet_dir(&mut self, dir: PathBuf) -> &mut Self {
```

2024-02-13 12:56 UTC, zancas submitted a review, later dismissed

2024-02-19 12:52 UTC, Oscar-Pepper requested changes
@AloeareV 's comments have not been resolved

2024-02-22 12:30 UTC, Oscar-Pepper approved these changes, later dismissed
wonderful

2024-02-22 12:31 UTC, Oscar-Pepper approved these changes, later dismissed

2024-02-22 12:41 UTC, Oscar-Pepper approved these changes, later dismissed

2024-02-23 10:34 UTC, Oscar-Pepper approved these changes

2024-02-23 10:35 UTC, merged