added TransactionRecordMap
zingolabs/zingolib pull request #901
Opened 2024-04-07 19:05 UTC by fluidvanadium

Another non-functional change

2024-04-08 18:41 UTC, Oscar-Pepper requested changes
The diff wasnt checked, the replace all ran rampant!

Also I have no idea what the purpose of this is?
Current *IS* a map, why does it need a map field?
I assume its to do with seperating a spending from viewing wallet but more context in the description is needed here. It feels like to me there is already a lot of nested unnecessary complexity with Wallet -> Context -> TxMap -> Current where the map of transactions should probably be a direct field of the wallet? This PR adds an extra layer

2024-04-08 18:41 UTC, Oscar-Pepper commented on zingolib/src/wallet/describe.rs
> +    /// Return a copy of the blocks current.maply in the wallet, needed to process possible reorgs
classic replace all :)

2024-04-08 22:09 UTC, zancas commented on zingolib/src/wallet/transactions/recording.rs
> +        // Read or create the current.map TxId
Typo?

2024-04-08 22:13 UTC, zancas commented
The benefit isn't obvious to me, but haven't tried too hard...

2024-04-08 22:53 UTC, zancas reviewed
If this is not necessary to land 317, then let's deprioritize it.

2024-04-08 22:54 UTC, zancas requested changes
Deprioritze non-essential work.

2024-04-09 18:09 UTC, zancas commented
Oh.. I think I see what's going on here...  I plan to reopen this..

2024-04-09 18:57 UTC, zancas commented
Superceded by #911

2024-04-09 18:57 UTC, closed without merging