Add unit test to transaction record map
zingolabs/zingolib pull request #914
Opened 2024-04-10 01:40 UTC by zancas

2024-04-10 14:51 UTC, fluidvanadium approved these changes, later dismissed
tested and acknowledged!

this is a wicked mocker pattern. i love it

2024-04-10 14:51 UTC, fluidvanadium commented
what thingie?

2024-04-10 22:57 UTC, zancas commented
Hello, I have resolved conflicts and merged latest dev.

2024-04-11 01:58 UTC, fluidvanadium requested changes, later dismissed

2024-04-11 01:58 UTC, fluidvanadium commented on zingolib/src/wallet/transaction_record.rs
> +    pub fn get_received_note<D>(
this fn is extra

2024-04-11 02:00 UTC, fluidvanadium commented on zingolib/src/wallet/transaction_record.rs
> +    pub fn get_received_note<D>(
i mean, it is superceded by the stuff in https://github.com/zingolabs/zingolib/pull/926/files#diff-cc4a46a7c665ac8355eec483ff4eb95fa7b6f50445e53bdfdd29414bec4233ac and wont be implemented

2024-04-11 02:04 UTC, fluidvanadium approved these changes
this is great! maybe i can duplicate these patterns for some more mocking stuff

2024-04-11 02:05 UTC, merged