Input source impl for TransactionRecordMap
zingolabs/zingolib pull request #926
Opened 2024-04-10 20:03 UTC by AloeareV

2024-04-10 20:07 UTC, fluidvanadium commented
im confused about the commit history on this one

2024-04-10 20:16 UTC, AloeareV commented
> im confused about the commit history on this one

Ah! Yes, I did a `git merge -p` so there's a merge commit that only takes a few of the changes from the 'merged in' commits.

2024-04-10 22:09 UTC, fluidvanadium requested changes
This is great! Can you move the TransactionRecordMap implementation to transaction_records_by_id?

2024-04-11 01:50 UTC, fluidvanadium commented
> This is great! Can you move the TransactionRecordMap implementation to transaction_records_by_id?

https://github.com/AloeareV/zingolib/pull/44

2024-04-11 02:34 UTC, zancas requested changes
I am seeing `integration-tests::integrations slow::timed_sync_interrupt` fail against `AloeareV:input_source`.

I am currently running the test against `dev`.   Depending on results I might loop it for 10 runs against each branch and leave that running.

We'll need to understand more about this test failure before we can land this PR.

2024-04-11 13:35 UTC, zancas requested changes
I *LOVE* that there's a new test here.
I prefer it to be darkside for integration-testing.   Can we port that test to darkside?

Also, I didn't check carefully..   are there unit-tests?

2024-04-11 13:38 UTC, zancas commented on zingolib/src/wallet/traits.rs
> +    fn get_nullifier_from_note_fvk_and_witness_position(
Any chance of a unit test for this?

2024-04-11 13:38 UTC, zancas commented on zingolib/src/wallet/traits.rs
> +    fn get_nullifier_from_note_fvk_and_witness_position(
unit test?

2024-04-11 13:38 UTC, zancas commented on zingolib/src/wallet/transaction_record.rs
> +    pub fn select_unspent_note_noteref_pairs_sapling(
Unit test?   doc-test?  doc-comment?

2024-04-11 13:39 UTC, zancas commented on zingolib/src/wallet/transaction_record.rs
> +    pub fn get_received_note<D>(
unit, doc-{test/comment} ?

2024-04-11 13:40 UTC, zancas commented on zingolib/src/wallet/transactions.rs
> +#[derive(Debug)]
This seems to be obsolete the type is named `TransactionRecordsById` in dev, and has moved.

2024-04-11 13:40 UTC, zancas commented on zingolib/src/wallet/transactions/trait_inputsource.rs
> +use orchard::note_encryption::OrchardDomain;
IIRC (If I Recall Correctly) this has moved, so this feature probably needs to merge in latest dev.

2024-04-11 17:20 UTC, zancas commented
Superceded by #935

2024-04-11 17:20 UTC, closed without merging