Enforce doc comments
zingolabs/zingolib pull request #934
Opened 2024-04-11 11:02 UTC by idky137

This PR will create clippy warnings for any pub functions that do not have Doc comments.

All current pub functions that do not already have a doc comment will be given "/// TODO: Add Doc Comment Here!". This way the code base will build without new warnings, but all new functions should be properly documented.

2024-04-12 19:21 UTC, fluidvanadium commented
can we try this against stable

2024-04-15 20:12 UTC, zancas commented on zingo-netutils/src/lib.rs
> +//! Zingo-Netutils
@AloeareV can you provide a more information doc-comment here?

2024-04-15 20:13 UTC, zancas commented on zingo-status/src/confirmation_status.rs
> +//! TODO: Add Mod Description Here!
@fluidvanadium can you make this doc-comment more useful?

2024-04-15 20:13 UTC, zancas commented on zingo-status/src/lib.rs
> +//! TODO: Add Crate Discription Here!
@fluidvanadium can you please add a comment here?

2024-04-16 08:53 UTC, idky137 commented
Finished adding todos. There is still one warning/error generated. This is because a function is being generated in the build process, I believe the way to solve this is to add "#[allow(missing_docs)]" to the module that is generating this function. However I am unaware of where this is.

2024-04-16 15:43 UTC, zancas requested changes

2024-04-16 15:43 UTC, zancas commented on zingo-memo/src/lib.rs
> +//! These memos will likely never be directly exposed to the user,
I prefer to remove this speculative statement.

2024-04-16 15:43 UTC, zancas commented on zingo-memo/src/lib.rs
> +//! but instead write down things on-chain, for recovery after rescan, etc
It's not clear to me that things that are procedurally generated/parsed by zingo-memo will always be mutually exclusive with end-user relevant content.   Perhaps we should remove this line, or refine it to be clearer?

2024-04-16 15:43 UTC, zancas commented on zingo-netutils/src/lib.rs
> +//! Zingo-Netutils
Are all of the current net-utils exclusively for test?

2024-04-16 16:02 UTC, AloeareV commented on zingo-memo/src/lib.rs
> +//! These memos will likely never be directly exposed to the user,
Why?

2024-04-16 16:05 UTC, AloeareV commented on zingo-memo/src/lib.rs
> +//! but instead write down things on-chain, for recovery after rescan, etc
> It's not clear to me that things that are procedurally generated/parsed by zingo-memo will always be mutually exclusive with end-user relevant content. Perhaps we should remove this line, or refine it to be clearer?

It's presumptive...but we can always re-evaluate it if we come up with a use-case. I can reword it to be a 'currently'.

2024-04-16 16:07 UTC, AloeareV commented on zingo-memo/src/lib.rs
> +//! but instead write down things on-chain, for recovery after rescan, etc
Reworded.

2024-04-16 17:13 UTC, zancas commented on zingoconfig/src/lib.rs
> +//! ZingConfig
@Oscar-Pepper can you please add a description of what this crate is, here?    No need for perfection, just enough to give a reader a general idea.  Fine to include `TODO`s for enhancements to the doc-comment.

2024-04-16 18:24 UTC, AloeareV submitted a review, later dismissed

2024-04-16 18:24 UTC, AloeareV commented on zingolib/src/wallet.rs
> +    /// Local state needed to submit [compact]block-requests to the proxy
Square brackets have special meaning in doc comments as intra-doc links, which causes this to fail cargo doc, as this is a broken link.

2024-04-16 18:25 UTC, AloeareV commented on zingolib/src/wallet.rs
> +    /// Local state needed to submit [compact]block-requests to the proxy
Oh hang on I will just fix this, that's easier than leaving a comment.

2024-04-17 01:32 UTC, fluidvanadium commented
how do i run this doc-comment completeness test locally?

2024-04-17 15:36 UTC, zancas submitted a review, later dismissed

2024-04-17 15:50 UTC, zancas approved these changes, later dismissed

2024-04-17 16:42 UTC, zancas submitted a review, later dismissed

2024-04-17 16:57 UTC, zancas approved these changes

2024-04-17 17:08 UTC, merged