Cleanup changelogs
zingolabs/zingolib pull request #950
Opened 2024-04-16 16:08 UTC by Oscar-Pepper

Cleans up existing changelogs into a uniform format which has bee nchecks for correctness. Also adds any missing changelogs.

2024-04-16 17:14 UTC, fluidvanadium requested changes

2024-04-16 17:14 UTC, fluidvanadium commented on zingolib/CHANGELOG.md
> +- `lightclient::LightClient::save`
because this mod implements methods, there is a clearer way to refer to them

2024-04-16 17:19 UTC, zancas submitted a review, later dismissed

2024-04-16 20:13 UTC, fluidvanadium approved these changes, later dismissed

2024-04-17 13:41 UTC, fluidvanadium approved these changes
great

2024-04-17 13:41 UTC, merged