add some comments to BlockManagementData
zingolabs/zingolib pull request #961
Opened 2024-04-18 19:10 UTC by fluidvanadium

I discovered this branch in one of my worktrees.

2024-04-19 11:51 UTC, Oscar-Pepper requested changes

2024-04-19 11:51 UTC, Oscar-Pepper commented on zingolib/src/blaze/block_management_reorg_detection.rs
> +    // List of all downloaded Compact Blocks in the current batch and
not sure what the capitals are for?

2024-04-19 11:51 UTC, Oscar-Pepper commented on zingolib/src/blaze/block_management_reorg_detection.rs
> +            // Read Lock for
comment seems incomplete

2024-04-19 11:51 UTC, Oscar-Pepper commented on zingolib/src/blaze/block_management_reorg_detection.rs
> +                    // starting with a block and searching until the top of the batch
I think the code is much more readable when not broken up by many comments. mabye describe the block in one comment above?

2024-04-19 11:51 UTC, Oscar-Pepper commented on zingolib/src/blaze/update_notes.rs
> +                        // we got the height the nullifier was spent at. now, we go back to the index because todO actually we needed the CompactTx, not just the height
comment seems incomplete

2024-04-22 20:47 UTC, fluidvanadium commented on zingolib/src/blaze/block_management_reorg_detection.rs
> +    // List of all downloaded Compact Blocks in the current batch and
because its a struct name.

2024-04-22 21:20 UTC, fluidvanadium commented on zingolib/src/blaze/update_notes.rs
> +                        // we got the height the nullifier was spent at. now, we go back to the index because todO actually we needed the CompactTx, not just the height
oops, these were unfinished! im so glad i got a chance to finish them

2024-04-23 02:09 UTC, fluidvanadium commented on zingolib/src/blaze/block_management_reorg_detection.rs
> +            // Read Lock for
completed

2024-04-23 17:24 UTC, zancas approved these changes

2024-04-23 17:24 UTC, merged